name: Build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Image
        run: docker-compose up -d

      - name: Clean
        run: docker-compose run --rm --volume `pwd`:/www website-portfolio make -C production/ clean

      - name: Build
        run: docker-compose run --rm --volume `pwd`:/www website-portfolio make -C production/ package

      - name: Store Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ticha-website # double zipping issue: https://github.com/actions/upload-artifact/issues/39
          path: production/release/ticha-website.zip

      - name: Release
        run: make -C production/ release AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_EC2_METADATA_DISABLED: "true" # https://github.com/actions/runner/issues/503

      # curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'

