name: Build
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: make -C production/ package

      - name: Store Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ticha-website # double zipping issue: https://github.com/actions/upload-artifact/issues/39
          path: production/release/ticha-website.zip

      # Temporary fix for crashing S3 release
      - name: Fix AWS CLI # https://github.com/aws/aws-cli/issues/5262
        run: aws --version && sudo apt-get install python3-setuptools && python3 -m pip install --user awscli && aws --version

      - name: Release
        run: make -C production/ release AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/YOURNAME/APPLICATION_NAME/actions/workflows/build.yaml/dispatches --data '{"ref": "master"}'

